const QUESTIONS_DB = {
  ue1: {
    name: "UE1 — Chimie & Biochimie", icon: "🧪", color: "#6366f1",
    questions: [
      { id:"ue1_001", text:"Configuration électronique du carbone (Z=6) à l'état fondamental ?",
        answers:[{id:"a",text:"1s² 2s² 2p²",correct:true},{id:"b",text:"1s² 2s² 2p⁴",correct:false},{id:"c",text:"1s² 2s¹ 2p³",correct:false},{id:"d",text:"1s² 2p⁴",correct:false},{id:"e",text:"2s² 2p²",correct:false}],
        explanation:"Le carbone (Z=6) a 6 électrons. Klechkowski : 1s²(2e) + 2s²(2e) + 2p²(2e). Donc 1s² 2s² 2p², avec 4 électrons de valence → tétravalent.",difficulty:1},
      { id:"ue1_002", text:"Parmi ces liaisons, lesquelles sont covalentes polaires ?",
        answers:[{id:"a",text:"O–H",correct:true},{id:"b",text:"C–C",correct:false},{id:"c",text:"N–H",correct:true},{id:"d",text:"H–H",correct:false},{id:"e",text:"C–Cl",correct:true}],
        explanation:"Polaire si ΔEN > 0,4. O-H (1,4), N-H (0,9), C-Cl (0,5) sont polaires. C-C et H-H sont apolaires (atomes identiques).",difficulty:2},
      { id:"ue1_003", text:"pH d'une solution HCl 0,01 mol/L ?",
        answers:[{id:"a",text:"pH = 1",correct:false},{id:"b",text:"pH = 2",correct:true},{id:"c",text:"pH = 7",correct:false},{id:"d",text:"pH = 12",correct:false},{id:"e",text:"pH = 0,01",correct:false}],
        explanation:"HCl acide fort : [H⁺] = 0,01 = 10⁻². pH = -log(10⁻²) = 2.",difficulty:1},
      { id:"ue1_004", text:"Propriétés des acides aminés essentiels ?",
        answers:[{id:"a",text:"Non synthétisés par l'organisme",correct:true},{id:"b",text:"Apportés par l'alimentation",correct:true},{id:"c",text:"Au nombre de 8 chez l'adulte",correct:true},{id:"d",text:"Sans groupement aminé",correct:false},{id:"e",text:"La valine est essentielle",correct:true}],
        explanation:"8 AA essentiels chez l'adulte (VILTMPFTL : Val, Ile, Leu, Thr, Met, Phe, Trp, Lys). L'organisme ne peut les synthétiser.",difficulty:2},
      { id:"ue1_005", text:"La saponification d'un triglycéride produit :",
        answers:[{id:"a",text:"Du glycérol",correct:true},{id:"b",text:"Des acides gras libres",correct:false},{id:"c",text:"Des savons (sels d'acides gras)",correct:true},{id:"d",text:"Du glucose",correct:false},{id:"e",text:"3 molécules de savon",correct:true}],
        explanation:"Triglycéride + 3 NaOH → Glycérol + 3 savons (carboxylates). Hydrolyse basique ≠ hydrolyse acide (acides gras libres).",difficulty:2},
      { id:"ue1_006", text:"Concernant les protéines, quelle(s) affirmation(s) est(sont) exacte(s) ?",
        answers:[{id:"a",text:"La structure primaire est la séquence d'acides aminés",correct:true},{id:"b",text:"L'hélice α est une structure secondaire",correct:true},{id:"c",text:"Les ponts disulfure stabilisent la structure quaternaire",correct:false},{id:"d",text:"La dénaturation est toujours irréversible",correct:false},{id:"e",text:"Le feuillet β est une structure secondaire",correct:true}],
        explanation:"Structure 1° = séquence AA. 2° = hélice α et feuillet β (liaisons H). Les ponts S-S stabilisent la structure tertiaire (pas quaternaire). La dénaturation peut être réversible (ex : protéines dénaturées par chaleur modérée).",difficulty:2},
      { id:"ue1_007", text:"Le pKa du groupe carboxylique (-COOH) des acides aminés est environ :",
        answers:[{id:"a",text:"2",correct:true},{id:"b",text:"4",correct:false},{id:"c",text:"7",correct:false},{id:"d",text:"9",correct:false},{id:"e",text:"12",correct:false}],
        explanation:"Le groupe -COOH a un pKa ≈ 2 (très acide). Le groupe -NH₃⁺ a un pKa ≈ 9-10. Au pH physiologique (7,4), -COOH est déprotoné (-COO⁻) et -NH₂ est protoné (-NH₃⁺).",difficulty:2},
      { id:"ue1_008", text:"Concernant l'ADN, laquelle de ces affirmations est fausse ?",
        answers:[{id:"a",text:"A s'apparie avec T par 2 liaisons H",correct:false},{id:"b",text:"G s'apparie avec C par 3 liaisons H",correct:false},{id:"c",text:"Les deux brins sont antiparallèles",correct:false},{id:"d",text:"A s'apparie avec U dans l'ADN",correct:true},{id:"e",text:"Le squelette est sucre-phosphate",correct:false}],
        explanation:"Dans l'ADN : A-T (2 H), G-C (3 H), brins antiparallèles, squelette désoxyribose-phosphate. L'uracile (U) est dans l'ARN, pas dans l'ADN (c'est T qui s'apparie avec A dans l'ADN).",difficulty:1},
    ]
  },
  ue2: {
    name: "UE2 — Biologie Cellulaire", icon: "🔬", color: "#10b981",
    questions: [
      { id:"ue2_001", text:"Concernant la membrane plasmique, lesquelles sont exactes ?",
        answers:[{id:"a",text:"Bicouche lipidique",correct:true},{id:"b",text:"Têtes hydrophiles vers l'extérieur",correct:true},{id:"c",text:"Le cholestérol rigidifie à haute température",correct:true},{id:"d",text:"Toutes les protéines sont transmembranaires",correct:false},{id:"e",text:"La fluidité augmente avec les chaînes longues saturées",correct:false}],
        explanation:"Bicouche phospholipidique : têtes hydrophiles vers l'eau, queues hydrophobes à l'intérieur. Cholestérol : rigidifie à T° élevée, fluidifie à basse T°. Protéines : transmembranaires, périphériques ou ancrées. Fluidité ↑ avec chaînes courtes/insaturées.",difficulty:2},
      { id:"ue2_002", text:"L'ordre correct des phases de la mitose est :",
        answers:[{id:"a",text:"Prophase → Métaphase → Anaphase → Télophase",correct:true},{id:"b",text:"Prophase → Anaphase → Métaphase → Télophase",correct:false},{id:"c",text:"La cytocinèse suit la télophase",correct:true},{id:"d",text:"La métaphase aligne les chromosomes sur la plaque équatoriale",correct:true},{id:"e",text:"L'anaphase sépare les chromatides sœurs",correct:true}],
        explanation:"PMAT : Prophase (condensation) → Métaphase (plaque équatoriale) → Anaphase (séparation chromatides) → Télophase (reformation noyaux) → Cytocinèse.",difficulty:1},
      { id:"ue2_003", text:"Quel(s) organite(s) possède(nt) leur propre ADN ?",
        answers:[{id:"a",text:"Mitochondries",correct:true},{id:"b",text:"Chloroplastes",correct:true},{id:"c",text:"Noyau",correct:false},{id:"d",text:"Ribosomes",correct:false},{id:"e",text:"Réticulum endoplasmique",correct:false}],
        explanation:"Mitochondries et chloroplastes : ADN circulaire, ribosomes 70S, reproduction par scissiparité (théorie endosymbiotique). Le noyau contient l'ADN nucléaire mais n'est pas semi-autonome.",difficulty:1},
      { id:"ue2_004", text:"Concernant la transcription chez les eucaryotes :",
        answers:[{id:"a",text:"Produit un ARN pré-messager",correct:true},{id:"b",text:"Se déroule dans le noyau",correct:true},{id:"c",text:"L'épissage élimine les introns",correct:true},{id:"d",text:"Utilise l'ARN pol II pour les ARNm",correct:true},{id:"e",text:"La traduction est simultanée dans le noyau",correct:false}],
        explanation:"Transcription nucléaire → pré-ARNm via ARN pol II → coiffe 5', poly-A 3', épissage (introns supprimés, exons joints). Traduction dans le cytoplasme uniquement (≠ procaryotes).",difficulty:2},
      { id:"ue2_005", text:"Le potentiel d'action neuronal est caractérisé par :",
        answers:[{id:"a",text:"Dépolarisation par entrée de Na⁺",correct:true},{id:"b",text:"Repolarisation par sortie de K⁺",correct:true},{id:"c",text:"Loi du tout ou rien",correct:true},{id:"d",text:"Amplitude variable selon le stimulus",correct:false},{id:"e",text:"Période réfractaire absolue pendant la dépolarisation",correct:true}],
        explanation:"PA : loi du tout ou rien (amplitude constante ≈110 mV). Dépolarisation (Na⁺ entre) → repolarisation (K⁺ sort) → hyperpolarisation. Période réfractaire absolue = impossible de déclencher un 2ème PA pendant la dépolarisation.",difficulty:3},
      { id:"ue2_006", text:"Concernant le réticulum endoplasmique rugueux (RER) :",
        answers:[{id:"a",text:"Il porte des ribosomes",correct:true},{id:"b",text:"Il synthétise les protéines destinées à la sécrétion",correct:true},{id:"c",text:"Il est impliqué dans la synthèse des lipides",correct:false},{id:"d",text:"Il est connecté à l'enveloppe nucléaire",correct:true},{id:"e",text:"Les protéines y sont glycosylées",correct:true}],
        explanation:"RER : ribosomes sur la membrane (aspect rugueux), synthèse des protéines sécrétées/membranaires, glycosylation co-traductionnelle, connecté à l'enveloppe nucléaire. La synthèse des lipides est assurée par le RE lisse (REL).",difficulty:2},
      { id:"ue2_007", text:"La méiose se distingue de la mitose car :",
        answers:[{id:"a",text:"Elle produit 4 cellules haploïdes",correct:true},{id:"b",text:"Elle comporte deux divisions successives",correct:true},{id:"c",text:"Elle permet la recombinaison génétique",correct:true},{id:"d",text:"Elle se déroule dans toutes les cellules somatiques",correct:false},{id:"e",text:"Les cellules filles sont génétiquement identiques",correct:false}],
        explanation:"Méiose : 2 divisions (méiose I réductionnelle + méiose II équationnelle) → 4 cellules haploïdes génétiquement différentes. La crossing-over (prophase I) assure la recombinaison. La méiose n'a lieu que dans les gonades.",difficulty:2},
    ]
  },
  ue3: {
    name: "UE3 — Biophysique", icon: "⚛️", color: "#f59e0b",
    questions: [
      { id:"ue3_001", text:"La pression artérielle systolique normale chez l'adulte est :",
        answers:[{id:"a",text:"< 120 mmHg",correct:true},{id:"b",text:"Mesurée lors de la contraction ventriculaire",correct:true},{id:"c",text:"Toujours supérieure à la diastolique",correct:true},{id:"d",text:"De l'ordre de 80 mmHg",correct:false},{id:"e",text:"Mesurée lors du relâchement ventriculaire",correct:false}],
        explanation:"Pression normale < 120/80 mmHg. Systolique = lors de la contraction ventriculaire (systole) → pression max. Diastolique (80 mmHg) = lors du relâchement.",difficulty:1},
      { id:"ue3_002", text:"La loi de Beer-Lambert : A = ε × l × c. Quelles affirmations sont vraies ?",
        answers:[{id:"a",text:"A est proportionnelle à la concentration",correct:true},{id:"b",text:"A est proportionnelle au trajet optique l",correct:true},{id:"c",text:"ε est le coefficient d'extinction molaire",correct:true},{id:"d",text:"A est proportionnelle à la transmittance T",correct:false},{id:"e",text:"A = log(I₀/I)",correct:true}],
        explanation:"Beer-Lambert : A = ε·l·c. A = log(I₀/I) = -log(T). Si T↑ alors A↓ (relation inverse, pas proportionnelle). ε en L·mol⁻¹·cm⁻¹, l en cm, c en mol/L.",difficulty:2},
      { id:"ue3_003", text:"L'équation de Nernst permet de calculer :",
        answers:[{id:"a",text:"Le potentiel d'équilibre d'un ion donné",correct:true},{id:"b",text:"E = (RT/zF) × ln([X]e/[X]i)",correct:true},{id:"c",text:"Le potentiel de membrane au repos",correct:false},{id:"d",text:"Le potentiel en fonction du gradient de concentration",correct:true},{id:"e",text:"Tient compte de tous les ions simultaneously",correct:false}],
        explanation:"Nernst calcule le potentiel d'équilibre d'un seul ion. Le Vm au repos (≈-70mV) utilise l'équation de Goldman (tous les ions). E_Nernst = (RT/zF)×ln([X]e/[X]i).",difficulty:3},
      { id:"ue3_004", text:"Le débit cardiaque (DC) est défini par :",
        answers:[{id:"a",text:"DC = Fréquence cardiaque × Volume d'éjection systolique",correct:true},{id:"b",text:"DC normal ≈ 5 L/min au repos",correct:true},{id:"c",text:"Le volume d'éjection systolique est ≈ 70 mL",correct:true},{id:"d",text:"DC = Pression artérielle / Résistances vasculaires",correct:true},{id:"e",text:"Le DC diminue à l'effort",correct:false}],
        explanation:"DC = FC × VES. Au repos : FC ≈ 70 bpm × VES ≈ 70 mL = 5 L/min. Loi d'Ohm hémodynamique : DC = PAM / RVS. À l'effort, DC peut atteindre 20-25 L/min.",difficulty:2},
      { id:"ue3_005", text:"Concernant les rayonnements ionisants :",
        answers:[{id:"a",text:"Les rayons γ ont le plus grand pouvoir de pénétration",correct:true},{id:"b",text:"Les rayons α sont stoppés par une feuille de papier",correct:true},{id:"c",text:"Les rayons β sont des électrons",correct:true},{id:"d",text:"Les rayons α ont le plus grand pouvoir ionisant",correct:true},{id:"e",text:"Les rayons γ sont des particules chargées",correct:false}],
        explanation:"α (noyaux He) : fort pouvoir ionisant, faible pénétration (papier). β (électrons) : pénétration intermédiaire (aluminium). γ (photons) : très fort pouvoir de pénétration (plomb nécessaire), non chargés.",difficulty:2},
    ]
  },
  ue4: {
    name: "UE4 — Évaluation diagnostique", icon: "📊", color: "#ef4444",
    questions: [
      { id:"ue4_001", text:"La sensibilité d'un test diagnostique est :",
        answers:[{id:"a",text:"VP / (VP + FN)",correct:true},{id:"b",text:"La proportion de malades détectés",correct:true},{id:"c",text:"VN / (VN + FP)",correct:false},{id:"d",text:"Un test sensible a peu de faux négatifs",correct:true},{id:"e",text:"Utile pour écarter un diagnostic",correct:true}],
        explanation:"Sensibilité = VP/(VP+FN) : proportion de malades bien détectés. Peu de FN → bon pour écarter un diagnostic (SnNout). La spécificité = VN/(VN+FP) : proportion de sains bien identifiés. Peu de FP → bon pour confirmer (SpPin).",difficulty:2},
      { id:"ue4_002", text:"La randomisation dans un essai clinique permet de :",
        answers:[{id:"a",text:"Équilibrer les facteurs de confusion",correct:true},{id:"b",text:"Éliminer le biais de sélection",correct:true},{id:"c",text:"Garantir la représentativité de l'échantillon",correct:false},{id:"d",text:"Assurer la comparabilité des groupes",correct:true},{id:"e",text:"Permettre l'inférence causale",correct:true}],
        explanation:"Randomisation : répartition aléatoire → équilibre des facteurs de confusion (connus et inconnus), comparabilité, inférence causale. Ne garantit pas la représentativité (rôle de l'échantillonnage). Élimine le biais de sélection.",difficulty:2},
      { id:"ue4_003", text:"La valeur prédictive positive (VPP) dépend de :",
        answers:[{id:"a",text:"La prévalence de la maladie",correct:true},{id:"b",text:"La sensibilité du test",correct:true},{id:"c",text:"La spécificité du test",correct:true},{id:"d",text:"Uniquement des caractéristiques intrinsèques du test",correct:false},{id:"e",text:"Elle augmente avec la prévalence",correct:true}],
        explanation:"VPP = VP/(VP+FP). Contrairement à Se et Sp (intrinsèques), la VPP dépend de la prévalence. Si prévalence ↑, VPP ↑ (plus de vrais positifs pour la même Se/Sp). D'où l'importance de la population testée.",difficulty:3},
      { id:"ue4_004", text:"Dans une étude cas-témoins :",
        answers:[{id:"a",text:"On part de la maladie pour remonter à l'exposition",correct:true},{id:"b",text:"On calcule un Odds Ratio",correct:true},{id:"c",text:"C'est une étude rétrospective",correct:true},{id:"d",text:"On peut calculer directement un risque relatif",correct:false},{id:"e",text:"Elle est adaptée aux maladies rares",correct:true}],
        explanation:"Étude cas-témoins : rétrospective, on compare des malades (cas) à des non-malades (témoins) sur leurs expositions passées. Mesure : Odds Ratio (pas de RR direct car on ne connaît pas l'incidence). Efficiente pour les maladies rares.",difficulty:2},
    ]
  },
  ue5: {
    name: "UE5 — Anatomie", icon: "🫀", color: "#8b5cf6",
    questions: [
      { id:"ue5_001", text:"Le cœur est situé dans :",
        answers:[{id:"a",text:"Le médiastin moyen",correct:true},{id:"b",text:"La cavité thoracique",correct:true},{id:"c",text:"La cavité abdominale",correct:false},{id:"d",text:"En position légèrement à gauche",correct:true},{id:"e",text:"Derrière le sternum",correct:true}],
        explanation:"Le cœur est dans le médiastin moyen (partie centrale du thorax), en position rétrosternale, légèrement dévié à gauche. Il est entouré du péricarde. Le médiastin est délimité latéralement par les plèvres.",difficulty:1},
      { id:"ue5_002", text:"Concernant le nerf sciatique :",
        answers:[{id:"a",text:"C'est le plus long nerf de l'organisme",correct:true},{id:"b",text:"Il naît du plexus sacré",correct:true},{id:"c",text:"Il innerve la face postérieure de la cuisse",correct:true},{id:"d",text:"Il naît du plexus brachial",correct:false},{id:"e",text:"Il se divise en nerf tibial et fibulaire commun",correct:true}],
        explanation:"Nerf sciatique : plus long nerf, issu du plexus sacré (L4-S3). Innerve face postérieure de cuisse, jambe, pied. Se divise en creux poplité en nerf tibial et nerf fibulaire commun (péronier).",difficulty:2},
      { id:"ue5_003", text:"L'artère coronaire gauche se divise en :",
        answers:[{id:"a",text:"Artère interventriculaire antérieure (IVA)",correct:true},{id:"b",text:"Artère circonflexe",correct:true},{id:"c",text:"Artère interventriculaire postérieure",correct:false},{id:"d",text:"Ces deux branches irriguent la majorité du ventricule gauche",correct:true},{id:"e",text:"L'IVA irrigue le septum interventriculaire",correct:true}],
        explanation:"Coronaire gauche → IVA (face antérieure VG + septum) + artère circonflexe (face latérale VG). L'artère interventriculaire postérieure est généralement une branche de la coronaire droite (dominance droite dans 85% des cas).",difficulty:2},
    ]
  }
};

const ACHIEVEMENTS = [
  { id:"first_quiz",  name:"Premier pas",     icon:"🎯", desc:"Terminer votre 1er quiz",        xp:50  },
  { id:"streak_3",   name:"En feu",           icon:"🔥", desc:"3 jours consécutifs",             xp:100 },
  { id:"streak_7",   name:"Une semaine !",    icon:"⚡", desc:"7 jours consécutifs",             xp:250 },
  { id:"perfect_quiz",name:"Parfait !",       icon:"⭐", desc:"100% à un quiz",                  xp:150 },
  { id:"questions_50",name:"50 questions",    icon:"📚", desc:"50 questions répondues",          xp:200 },
  { id:"exam_done",  name:"Candidat",         icon:"🏆", desc:"Terminer un examen blanc",        xp:300 },
];
